### ISSUE TITLE
Incorrect reference to "Song" class

### ISSUE THREAD

**Issue by kjoewill** [learn-co-curriculum/ruby-advanced-class-methods-readme#22]
The first paragraph references a Song class:

> **Advanced Class Methods**
>Consider the method .all on the Song class––Song.all

However, the example presented is actually the Person class

```
class Person
    attr_accessor :name
    @@all = []
 
  def initialize(name)
    @name = name
  end
 
  def self.all
    @@all
  end
 
end
```

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this
issue. 💙
