### ISSUE TITLE
Typo, word "to" missing 2nd sentence

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/ruby-advanced-class-methods-readme#23]
(Within #initialize, an instance method, self will refer to an instance, not the entire class. In order to access Person.all, we need go from the instance, self, to the class––self.class––returning Person, and then invoke the Person.all method).

**Comment by drakeltheryuujin** [comment]
Hi @ccklight,

The README has been updated with the correction. Thanks for contributing 💙
