### ISSUE TITLE
Object Oriented key mechanics Video

### ISSUE THREAD

**Issue by katreesedarcene** [learn-co-curriculum/ruby-advanced-class-methods-readme#25]
Hi

I really think this video should've been redone because of the persons camera playing during the lecture.  Though there is a lot of info in the video, it comes off as unprofessional for a school and its also distracting while you are trying to learn.
 Thanks

**Comment by sgharms** [comment]
@katreesedarcene Seems reasonable. Also, this is 3 hours of video content! Yikes. We can make this simpler and less live-code feeling. This is not something I can instantly resolve, but we do have a video production effort afoot. I'll move this over to that team.
